name: Build

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-linux-musl]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1

    - name: Build Toolchain
      uses: docker/build-push-action@v3
      with:
        build-args: TARGET=${{ matrix.target }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        outputs: type=tar,dest=${{ matrix.target }}.tar
        target: deploy

    - name: Test Toolchain
      run: xz -k ${{ matrix.target }}.tar && tar -xf ${{ matrix.target }}.tar && make SRC_DIR=test CXX=bin/${{ matrix.target }}-g++ CXXFLAGS='-O2' -f test/Makefile version tests
